In [199]:
import pandas as pd

In [200]:
def load_json(filename):
    with open(filename, 'r') as handle:
        res = pd.read_json(path_or_buf = handle, orient = 'values')
        res.columns = res.iloc[0]
        res = res.drop(0, axis=0).reset_index().drop('index', axis=1)

    return res

In [201]:
race_var_key = pd.read_csv('Race variable key.csv').set_index('Name')

In [202]:
raceBX = load_json('BX_race.json')
#drop annotation type entries, these have no values
for column in raceBX.columns:
    if column[-1:] == 'A':
        raceBX = raceBX.drop(column, axis=1 )

raceBX = raceBX.rename(race_var_key.to_dict()['Label'], axis=1)

raceBK = load_json('BK_race.json')
#drop annotation type entries, these have no values
for column in raceBK.columns:
    if column[-1:] == 'A':
        raceBK = raceBK.drop(column, axis=1 )

raceBK = raceBK.rename(race_var_key.to_dict()['Label'], axis=1)

raceMH = load_json('MH_race.json')
#drop annotation type entries, these have no values
for column in raceMH.columns:
    if column[-1:] == 'A':
        raceMH = raceMH.drop(column, axis=1 )

raceMH = raceMH.rename(race_var_key.to_dict()['Label'], axis=1)

raceQN = load_json('QN_race.json')
#drop annotation type entries, these have no values
for column in raceQN.columns:
    if column[-1:] == 'A':
        raceQN = raceQN.drop(column, axis=1 )

raceQN = raceQN.rename(race_var_key.to_dict()['Label'], axis=1)

raceSI = load_json('SI_race.json')
#drop annotation type entries, these have no values
for column in raceSI.columns:
    if column[-1:] == 'A':
        raceSI = raceSI.drop(column, axis=1 )

raceSI = raceSI.rename(race_var_key.to_dict()['Label'], axis=1)

In [203]:
raceALL = pd.concat([raceBK, raceBX, raceMH, raceQN, raceSI], ignore_index = True)

In [204]:
raceALL.shape[0] == raceBK.shape[0]+ raceBX.shape[0] + raceMH.shape[0] + raceQN.shape[0] + raceSI.shape[0]

True

In [205]:
raceALL.head()

,GEO_ID,Est: Total,MoE: Total,Est: Total: White alone,MoE: Total: White alone,Est: Total: Black or African American alone,MoE: Total: Black or African American alone,Est: Total: American Indian and Alaska Native alone,MoE: Total: American Indian and Alaska Native alone,Est: Total: Asian alone,...,Est: Total: Two or more races,MoE: Total: Two or more races,Est: Total: Two or more races: Two races including Some other race,MoE: Total: Two or more races: Two races including Some other race,"Est: Total: Two or more races: Two races excluding Some other race, and three or more races","MoE: Total: Two or more races: Two races excluding Some other race, and three or more races",NAME,state,county,tract
0,1400000US36047025300,2540,379,894,235,1313,326,0,11,137,...,19,27,0,11,19,27,"Census Tract 253, Kings County, New York",36,047,025300
1,1400000US36047028800,3495,431,1547,317,8,12,0,11,1215,...,18,34,18,34,0,11,"Census Tract 288, Kings County, New York",36,047,028800
2,1400000US36047037300,4110,466,619,270,2638,373,9,14,60,...,58,93,6,10,52,92,"Census Tract 373, Kings County, New York",36,047,037300
3,1400000US36047040500,1539,234,346,222,730,200,0,11,81,...,39,44,10,7,29,43,"Census Tract 405, Kings County, New York",36,047,040500
4,1400000US36047047200,2931,350,2901,349,17,17,0,11,0,...,13,18,8,16,5,9,"Census Tract 472, Kings County, New York",36,047,047200

In [206]:
hisp_var_key = pd.read_csv('Hispanic variable key.csv').set_index('Name')

In [207]:
hispBX = load_json('BX_hisp.json')
#drop annotation type entries, these have no values
for column in hispBX.columns:
    if column[-1:] == 'A':
        hispBX = hispBX.drop(column, axis=1 )

hispBX = hispBX.rename(hisp_var_key.to_dict()['Label'], axis=1)

hispBK = load_json('BK_hisp.json')
#drop annotation type entries, these have no values
for column in hispBK.columns:
    if column[-1:] == 'A':
        hispBK = hispBK.drop(column, axis=1 )

hispBK = hispBK.rename(hisp_var_key.to_dict()['Label'], axis=1)

hispMH = load_json('MH_hisp.json')
#drop annotation type entries, these have no values
for column in hispMH.columns:
    if column[-1:] == 'A':
        hispMH = hispMH.drop(column, axis=1 )

hispMH = hispMH.rename(hisp_var_key.to_dict()['Label'], axis=1)

hispQN = load_json('QN_hisp.json')
#drop annotation type entries, these have no values
for column in hispQN.columns:
    if column[-1:] == 'A':
        hispQN = hispQN.drop(column, axis=1 )

hispQN = hispQN.rename(hisp_var_key.to_dict()['Label'], axis=1)

hispSI = load_json('SI_hisp.json')
#drop annotation type entries, these have no values
for column in hispSI.columns:
    if column[-1:] == 'A':
        hispSI = hispSI.drop(column, axis=1 )

hispSI = hispSI.rename(hisp_var_key.to_dict()['Label'], axis=1)

In [208]:
hispALL = pd.concat([hispBK, hispBX, hispMH, hispQN, hispSI], ignore_index = True)

In [209]:
hispALL.shape[0] == hispBK.shape[0]+ hispBX.shape[0] + hispMH.shape[0] + hispQN.shape[0] + hispSI.shape[0]

True

In [210]:
poverty_var_key = pd.read_csv('Poverty variable key.csv').set_index('Name')

In [211]:
povertyBX = load_json('BX_poverty.json')
#drop annotation type entries, these have no values
for column in povertyBX.columns:
    if column[-1:] == 'A':
        povertyBX = povertyBX.drop(column, axis=1 )

povertyBX = povertyBX.rename(poverty_var_key.to_dict()['Label'], axis=1)

povertyBK = load_json('BK_poverty.json')
#drop annotation type entries, these have no values
for column in povertyBK.columns:
    if column[-1:] == 'A':
        povertyBK = povertyBK.drop(column, axis=1 )

povertyBK = povertyBK.rename(poverty_var_key.to_dict()['Label'], axis=1)

povertyMH = load_json('MH_poverty.json')
#drop annotation type entries, these have no values
for column in povertyMH.columns:
    if column[-1:] == 'A':
        povertyMH = povertyMH.drop(column, axis=1 )

povertyMH = povertyMH.rename(poverty_var_key.to_dict()['Label'], axis=1)

povertyQN = load_json('QN_poverty.json')
#drop annotation type entries, these have no values
for column in povertyQN.columns:
    if column[-1:] == 'A':
        povertyQN = povertyQN.drop(column, axis=1 )

povertyQN = povertyQN.rename(poverty_var_key.to_dict()['Label'], axis=1)

povertySI = load_json('SI_poverty.json')
#drop annotation type entries, these have no values
for column in povertySI.columns:
    if column[-1:] == 'A':
        povertySI = povertySI.drop(column, axis=1 )

povertySI = povertySI.rename(poverty_var_key.to_dict()['Label'], axis=1)

In [212]:
povertyALL = pd.concat([povertyBK, povertyBX, povertyMH, povertyQN, povertySI], ignore_index = True)

In [213]:
povertyALL.shape[0] == povertyBK.shape[0]+ povertyBX.shape[0] + povertyMH.shape[0] + povertyQN.shape[0] + povertySI.shape[0]

True

In [214]:
povertyrace_var_key = pd.read_csv('Poverty Race variable key.csv').set_index('Name')
povertyraceBX = load_json('BX_povertyrace.json')
#drop annotation type entries, these have no values
for column in povertyraceBX.columns:
    if column[-1:] == 'A':
        povertyraceBX = povertyraceBX.drop(column, axis=1 )

povertyraceBX = povertyraceBX.rename(povertyrace_var_key.to_dict()['Label'], axis=1)

povertyraceBK = load_json('BK_povertyrace.json')
#drop annotation type entries, these have no values
for column in povertyraceBK.columns:
    if column[-1:] == 'A':
        povertyraceBK = povertyraceBK.drop(column, axis=1 )

povertyraceBK = povertyraceBK.rename(povertyrace_var_key.to_dict()['Label'], axis=1)

povertyraceMH = load_json('MH_povertyrace.json')
#drop annotation type entries, these have no values
for column in povertyraceMH.columns:
    if column[-1:] == 'A':
        povertyraceMH = povertyraceMH.drop(column, axis=1 )

povertyraceMH = povertyraceMH.rename(povertyrace_var_key.to_dict()['Label'], axis=1)

povertyraceQN = load_json('QN_povertyrace.json')
#drop annotation type entries, these have no values
for column in povertyraceQN.columns:
    if column[-1:] == 'A':
        povertyraceQN = povertyraceQN.drop(column, axis=1)

povertyraceQN = povertyraceQN.rename(povertyrace_var_key.to_dict()['Label'], axis=1)

povertyraceSI = load_json('SI_povertyrace.json')
#drop annotation type entries, these have no values
for column in povertyraceSI.columns:
    if column[-1:] == 'A':
        povertyraceSI = povertyraceSI.drop(column, axis=1 )

povertyraceSI = povertyraceSI.rename(povertyrace_var_key.to_dict()['Label'], axis=1)

In [215]:
povertyraceALL = pd.concat([povertyraceBK, povertyraceBX, povertyraceMH, povertyraceQN, povertyraceSI], ignore_index = True)
povertyraceALL.shape[0] == povertyraceBK.shape[0]+ povertyraceBX.shape[0] + povertyraceMH.shape[0] + povertyraceQN.shape[0] + povertyraceSI.shape[0]

True

In [216]:
raceALL = raceALL.set_index('GEO_ID')
hispALL = hispALL.set_index('GEO_ID')

In [217]:
povertyALL['GEO_ID'] = '1400000US36'+povertyALL['county']+povertyALL['tract']
povertyraceALL['GEO_ID'] ='1400000US36'+povertyraceALL['county']+povertyraceALL['tract']

In [218]:
povertyALL = povertyALL.set_index('GEO_ID')
povertyraceALL = povertyraceALL.set_index('GEO_ID')

In [219]:
ACSfinal = pd.concat([raceALL, hispALL, povertyALL, povertyraceALL], axis=1, ignore_index=False)

In [220]:
ACSfinal.shape[1] == raceALL.shape[1]+hispALL.shape[1]+povertyALL.shape[1]+povertyraceALL.shape[1]

True

In [221]:
ACSfinal.shape[0] == raceALL.shape[0]

True

In [222]:
ACSfinal = ACSfinal.loc[:,~ACSfinal.columns.duplicated()]

In [223]:
ACSfinal.to_csv('ACS 5 year estimates 2011-2015 NYC tracts.csv')

In [224]:
ACSfinal

,Est: Total,MoE: Total,Est: Total: White alone,MoE: Total: White alone,Est: Total: Black or African American alone,MoE: Total: Black or African American alone,Est: Total: American Indian and Alaska Native alone,MoE: Total: American Indian and Alaska Native alone,Est: Total: Asian alone,MoE: Total: Asian alone,...,Est: Poverty Status Past 12 Months,Est: Poverty Status Past 12 Months (White),Est: Poverty Status Past 12 Months (Black),Est: Poverty Status Past 12 Months (Native American),Est: Poverty Status Past 12 Months (Asian),Est: Poverty Status Past 12 Months (Native Hawiian/Pacific Islander),Est: Poverty Status Past 12 Months (Other),Est: Poverty Status Past 12 Months (Two or more races),Est: Poverty Status Past 12 Months (Non-Hispanic White),Est: Poverty Status Past 12 Months (Hispanic or Latino)
1400000US36047025300,2540,379,894,235,1313,326,0,11,137,98,...,656,284,178,0,111,0,83,0,231,159
1400000US36047028800,3495,431,1547,317,8,12,0,11,1215,325,...,769,293,8,0,236,0,232,0,279,246
1400000US36047037300,4110,466,619,270,2638,373,9,14,60,70,...,1401,255,713,0,0,0,433,0,80,623
1400000US36047040500,1539,234,346,222,730,200,0,11,81,71,...,437,111,259,0,49,0,16,2,16,113
1400000US36047047200,2931,350,2901,349,17,17,0,11,0,11,...,684,679,0,0,0,0,0,5,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1400000US36085030302,6279,488,3201,489,1365,310,0,16,899,193,...,1191,671,142,0,265,0,113,0,281,516
1400000US36085031901,2550,426,505,268,1663,442,0,11,161,130,...,1002,200,731,0,0,0,71,0,33,329
1400000US36085031902,4611,479,1238,318,2943,421,43,58,42,44,...,1899,367,1286,13,18,0,135,80,89,519
1400000US36085032300,1131,151,514,119,336,128,4,11,0,11,...,232,101,81,0,0,0,50,0,45,106
1400000US36085990100,0,11,0,11,0,11,0,11,0,11,...,0,0,0,0,0,0,0,0,0,0